version: 2
updates:
  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    groups:
      terraform-maintenance:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: hashicorp/aws
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    groups:
      actions-maintenance:
        patterns:
          - "*"
